// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CleanupShotsReducer from "../cleanup_shots_reducer";
import DestroyBlocksPhysicsReducer from "../destroy_blocks_physics_reducer";
import FireWeaponReducer from "../fire_weapon_reducer";
import ReloadWeaponReducer from "../reload_weapon_reducer";
import RespawnReducer from "../respawn_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetUsernameReducer from "../set_username_reducer";
import UpdatePositionReducer from "../update_position_reducer";

export type CleanupShotsParams = __Infer<typeof CleanupShotsReducer>;
export type DestroyBlocksPhysicsParams = __Infer<typeof DestroyBlocksPhysicsReducer>;
export type FireWeaponParams = __Infer<typeof FireWeaponReducer>;
export type ReloadWeaponParams = __Infer<typeof ReloadWeaponReducer>;
export type RespawnParams = __Infer<typeof RespawnReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;

