// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  abilityType: __t.u8().name("ability_type"),
  get pos() {
    return Vec3;
  },
  active: __t.bool(),
  respawnAt: __t.timestamp().name("respawn_at"),
  createdAt: __t.timestamp().name("created_at"),
});
