// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  xs: __t.array(__t.i32()),
  zs: __t.array(__t.i32()),
  fromYs: __t.array(__t.i32()).name("from_ys"),
  toYs: __t.array(__t.i32()).name("to_ys"),
  blockTypes: __t.byteArray().name("block_types"),
  createdAt: __t.timestamp().name("created_at"),
});
