// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  blocksX: __t.array(__t.i32()).name("blocks_x"),
  blocksY: __t.array(__t.i32()).name("blocks_y"),
  blocksZ: __t.array(__t.i32()).name("blocks_z"),
  blockTypes: __t.byteArray().name("block_types"),
  motionMode: __t.u8().name("motion_mode"),
  get pivot() {
    return Vec3;
  },
  get axis() {
    return Vec3;
  },
  get drift() {
    return Vec3;
  },
  get fractureOrigin() {
    return Vec3.name("fracture_origin");
  },
  get fractureDir() {
    return Vec3.name("fracture_dir");
  },
  angAccel: __t.f32().name("ang_accel"),
  initialAngVel: __t.f32().name("initial_ang_vel"),
  gravityScale: __t.f32().name("gravity_scale"),
  fractureSpeed: __t.f32().name("fracture_speed"),
  lifetimeMs: __t.u32().name("lifetime_ms"),
  createdAt: __t.timestamp().name("created_at"),
});
