// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  blocksX: __t.array(__t.i32()).name("blocks_x"),
  blocksY: __t.array(__t.i32()).name("blocks_y"),
  blocksZ: __t.array(__t.i32()).name("blocks_z"),
  blockTypes: __t.byteArray().name("block_types"),
  createdAt: __t.timestamp().name("created_at"),
});
