// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
  DestroyedBlock,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  origin: __t.identity(),
  get pos() {
    return Vec3;
  },
  radius: __t.f32(),
  weapon: __t.u8(),
  get destroyedBlocks() {
    return __t.array(DestroyedBlock).name("destroyed_blocks");
  },
  createdAt: __t.timestamp().name("created_at"),
});
