// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  roundNumber: __t.u32().name("round_number"),
  state: __t.u8(),
  phaseStartedAt: __t.timestamp().name("phase_started_at"),
  phaseEndsAt: __t.timestamp().name("phase_ends_at"),
  timeRemainingSecs: __t.u32().name("time_remaining_secs"),
});
