// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
  Rotation,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  entityId: __t.u64().name("entity_id"),
  username: __t.string(),
  characterPreset: __t.u8().name("character_preset"),
  movementFlags: __t.u8().name("movement_flags"),
  get pos() {
    return Vec3;
  },
  get vel() {
    return Vec3;
  },
  get rot() {
    return Rotation;
  },
  health: __t.i32(),
  maxHealth: __t.i32().name("max_health"),
  currentWeapon: __t.u8().name("current_weapon"),
  kills: __t.u32(),
  deaths: __t.u32(),
  spawnProtected: __t.bool().name("spawn_protected"),
  online: __t.bool(),
  mountedVehicleId: __t.u64().name("mounted_vehicle_id"),
  joinedAt: __t.timestamp().name("joined_at"),
  lastDamageTime: __t.timestamp().name("last_damage_time"),
});
