// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
  Rotation,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  get pos() {
    return Vec3;
  },
  get rot() {
    return Rotation;
  },
  health: __t.i32(),
  maxHealth: __t.i32().name("max_health"),
  currentWeapon: __t.u8().name("current_weapon"),
  kills: __t.u32(),
  deaths: __t.u32(),
  online: __t.bool(),
  joinedAt: __t.timestamp().name("joined_at"),
});
