// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  profileId: __t.u64().primaryKey().name("profile_id"),
  displayName: __t.string().name("display_name"),
  totalKills: __t.u32().name("total_kills"),
  totalDeaths: __t.u32().name("total_deaths"),
  timePlayedSecs: __t.u64().name("time_played_secs"),
  bestStreak: __t.u32().name("best_streak"),
  createdAt: __t.timestamp().name("created_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
});
