// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  ammoRifle: __t.i32().name("ammo_rifle"),
  ammoShotgun: __t.i32().name("ammo_shotgun"),
  ammoRpg: __t.i32().name("ammo_rpg"),
  ammoMachineGun: __t.i32().name("ammo_machine_gun"),
  ammoGrenade: __t.i32().name("ammo_grenade"),
  lastFireTime: __t.timestamp().name("last_fire_time"),
});
