// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  Vec3,
} from "./types";

export default {
  get shotOrigin() {
    return Vec3;
  },
  get impactPos() {
    return Vec3;
  },
  get direction() {
    return Vec3;
  },
  weapon: __t.u8(),
  travelTimeMs: __t.u32(),
  hitPlayers: __t.array(__t.identity()),
  hitVehicles: __t.array(__t.u64()),
  get hitBlocks() {
    return __t.array(Vec3);
  },
};
