// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  shooter: __t.identity(),
  get origin() {
    return Vec3;
  },
  get direction() {
    return Vec3;
  },
  get hitPos() {
    return Vec3.name("hit_pos");
  },
  hasHit: __t.bool().name("has_hit"),
  weapon: __t.u8(),
  firedAt: __t.timestamp().name("fired_at"),
});
