// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  senderName: __t.string(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const DestroyedBlock = __t.object("DestroyedBlock", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  blockType: __t.u8(),
});
export type DestroyedBlock = __Infer<typeof DestroyedBlock>;

export const DetachCleanup = __t.object("DetachCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DetachCleanup = __Infer<typeof DetachCleanup>;

export const DetachEvent = __t.object("DetachEvent", {
  id: __t.u64(),
  blocksX: __t.array(__t.i32()),
  blocksY: __t.array(__t.i32()),
  blocksZ: __t.array(__t.i32()),
  blockTypes: __t.byteArray(),
  motionMode: __t.u8(),
  get pivot() {
    return Vec3;
  },
  get axis() {
    return Vec3;
  },
  get drift() {
    return Vec3;
  },
  get fractureOrigin() {
    return Vec3;
  },
  get fractureDir() {
    return Vec3;
  },
  angAccel: __t.f32(),
  initialAngVel: __t.f32(),
  gravityScale: __t.f32(),
  fractureSpeed: __t.f32(),
  lifetimeMs: __t.u32(),
  createdAt: __t.timestamp(),
});
export type DetachEvent = __Infer<typeof DetachEvent>;

export const Entity = __t.object("Entity", {
  id: __t.u64(),
  kind: __t.u8(),
  subtype: __t.u8(),
  get pos() {
    return Vec3;
  },
  get vel() {
    return Vec3;
  },
  get rot() {
    return Rotation;
  },
  scale: __t.f32(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Entity = __Infer<typeof Entity>;

export const EnvironmentTick = __t.object("EnvironmentTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EnvironmentTick = __Infer<typeof EnvironmentTick>;

export const ExplosionEvent = __t.object("ExplosionEvent", {
  id: __t.u64(),
  origin: __t.identity(),
  get pos() {
    return Vec3;
  },
  radius: __t.f32(),
  weapon: __t.u8(),
  get destroyedBlocks() {
    return __t.array(DestroyedBlock);
  },
  createdAt: __t.timestamp(),
});
export type ExplosionEvent = __Infer<typeof ExplosionEvent>;

export const GrenadeProjectile = __t.object("GrenadeProjectile", {
  id: __t.u64(),
  owner: __t.identity(),
  get pos() {
    return Vec3;
  },
  get vel() {
    return Vec3;
  },
  fuseRemainingMs: __t.u32(),
  createdAt: __t.timestamp(),
});
export type GrenadeProjectile = __Infer<typeof GrenadeProjectile>;

export const GrenadeTick = __t.object("GrenadeTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GrenadeTick = __Infer<typeof GrenadeTick>;

export const HealthRegenTick = __t.object("HealthRegenTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type HealthRegenTick = __Infer<typeof HealthRegenTick>;

export const KillEvent = __t.object("KillEvent", {
  id: __t.u64(),
  killerName: __t.string(),
  victimName: __t.string(),
  weapon: __t.u8(),
  createdAt: __t.timestamp(),
});
export type KillEvent = __Infer<typeof KillEvent>;

export const MapResetTimer = __t.object("MapResetTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MapResetTimer = __Infer<typeof MapResetTimer>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  entityId: __t.u64(),
  username: __t.string(),
  characterPreset: __t.u8(),
  get pos() {
    return Vec3;
  },
  get vel() {
    return Vec3;
  },
  get rot() {
    return Rotation;
  },
  health: __t.i32(),
  maxHealth: __t.i32(),
  currentWeapon: __t.u8(),
  kills: __t.u32(),
  deaths: __t.u32(),
  spawnProtected: __t.bool(),
  online: __t.bool(),
  mountedVehicleId: __t.u64(),
  joinedAt: __t.timestamp(),
  lastDamageTime: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerAmmo = __t.object("PlayerAmmo", {
  id: __t.u64(),
  identity: __t.identity(),
  weaponIndex: __t.u8(),
  ammo: __t.i32(),
});
export type PlayerAmmo = __Infer<typeof PlayerAmmo>;

export const PlayerFireState = __t.object("PlayerFireState", {
  identity: __t.identity(),
  lastFireTime: __t.timestamp(),
});
export type PlayerFireState = __Infer<typeof PlayerFireState>;

export const PlayerLoadout = __t.object("PlayerLoadout", {
  username: __t.string(),
  slot1: __t.u8(),
  slot2: __t.u8(),
  slot3: __t.u8(),
  updatedAt: __t.timestamp(),
});
export type PlayerLoadout = __Infer<typeof PlayerLoadout>;

export const PlayerMovementState = __t.object("PlayerMovementState", {
  identity: __t.identity(),
  get lastPos() {
    return Vec3;
  },
  lastUpdate: __t.timestamp(),
  violationCount: __t.u32(),
});
export type PlayerMovementState = __Infer<typeof PlayerMovementState>;

export const PlayerSession = __t.object("PlayerSession", {
  identity: __t.identity(),
  connectionId: __t.connectionId(),
  connectedAt: __t.timestamp(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const Rotation = __t.object("Rotation", {
  yaw: __t.f32(),
  pitch: __t.f32(),
});
export type Rotation = __Infer<typeof Rotation>;

export const ShotCleanup = __t.object("ShotCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ShotCleanup = __Infer<typeof ShotCleanup>;

export const ShotEvent = __t.object("ShotEvent", {
  id: __t.u64(),
  shooter: __t.identity(),
  get origin() {
    return Vec3;
  },
  get direction() {
    return Vec3;
  },
  get hitPos() {
    return Vec3;
  },
  hasHit: __t.bool(),
  weapon: __t.u8(),
  sourceVehicle: __t.u64(),
  firedAt: __t.timestamp(),
});
export type ShotEvent = __Infer<typeof ShotEvent>;

export const Vec3 = __t.object("Vec3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type Vec3 = __Infer<typeof Vec3>;

export const Vehicle = __t.object("Vehicle", {
  entityId: __t.u64(),
  vehicleType: __t.u8(),
  pilotIdentity: __t.option(__t.identity()),
  seatCount: __t.u8(),
  inputForward: __t.f32(),
  inputStrafe: __t.f32(),
  inputLift: __t.f32(),
  inputYaw: __t.f32(),
  boosting: __t.bool(),
  rotorSpin: __t.f32(),
  health: __t.i32(),
  weaponType: __t.u8(),
  weaponAmmoPrimary: __t.i32(),
  weaponAmmoSecondary: __t.i32(),
  weaponLastFire: __t.timestamp(),
  createdAt: __t.timestamp(),
  lastInputAt: __t.timestamp(),
});
export type Vehicle = __Infer<typeof Vehicle>;

export const VehicleDestroyEvent = __t.object("VehicleDestroyEvent", {
  id: __t.u64(),
  entityId: __t.u64(),
  vehicleType: __t.u8(),
  get pos() {
    return Vec3;
  },
  get rot() {
    return Rotation;
  },
  createdAt: __t.timestamp(),
});
export type VehicleDestroyEvent = __Infer<typeof VehicleDestroyEvent>;

export const VehicleTick = __t.object("VehicleTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type VehicleTick = __Infer<typeof VehicleTick>;

export const WorldChunk = __t.object("WorldChunk", {
  chunkId: __t.u32(),
  cx: __t.u8(),
  cy: __t.u8(),
  cz: __t.u8(),
  data: __t.byteArray(),
  version: __t.u64(),
});
export type WorldChunk = __Infer<typeof WorldChunk>;

export const WorldConfig = __t.object("WorldConfig", {
  id: __t.u32(),
  seed: __t.u64(),
  roundNumber: __t.u32(),
  roundStart: __t.timestamp(),
});
export type WorldConfig = __Infer<typeof WorldConfig>;

export const WorldEnvironment = __t.object("WorldEnvironment", {
  id: __t.u32(),
  timeOfDay: __t.f32(),
  weather: __t.u8(),
  windSpeed: __t.f32(),
  cloudDensity: __t.f32(),
  fogDensity: __t.f32(),
  lastWeatherChange: __t.timestamp(),
});
export type WorldEnvironment = __Infer<typeof WorldEnvironment>;

