// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  senderName: __t.string(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const DestroyedBlock = __t.object("DestroyedBlock", {
  id: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  destroyedBy: __t.identity(),
  destroyedAt: __t.timestamp(),
});
export type DestroyedBlock = __Infer<typeof DestroyedBlock>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  get pos() {
    return Vec3;
  },
  get rot() {
    return Rotation;
  },
  health: __t.i32(),
  maxHealth: __t.i32(),
  currentWeapon: __t.u8(),
  kills: __t.u32(),
  deaths: __t.u32(),
  online: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Rotation = __t.object("Rotation", {
  yaw: __t.f32(),
  pitch: __t.f32(),
});
export type Rotation = __Infer<typeof Rotation>;

export const ShotEvent = __t.object("ShotEvent", {
  id: __t.u64(),
  shooter: __t.identity(),
  get origin() {
    return Vec3;
  },
  get direction() {
    return Vec3;
  },
  weapon: __t.u8(),
  firedAt: __t.timestamp(),
});
export type ShotEvent = __Infer<typeof ShotEvent>;

export const Vec3 = __t.object("Vec3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type Vec3 = __Infer<typeof Vec3>;

