// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  vehicleType: __t.u8().name("vehicle_type"),
  pilotIdentity: __t.option(__t.identity()).name("pilot_identity"),
  seatCount: __t.u8().name("seat_count"),
  inputForward: __t.f32().name("input_forward"),
  inputStrafe: __t.f32().name("input_strafe"),
  inputLift: __t.f32().name("input_lift"),
  inputYaw: __t.f32().name("input_yaw"),
  boosting: __t.bool(),
  inputSeq: __t.u32().name("input_seq"),
  ackedInputSeq: __t.u32().name("acked_input_seq"),
  simTick: __t.u64().name("sim_tick"),
  simUpdatedAt: __t.timestamp().name("sim_updated_at"),
  rotorSpin: __t.f32().name("rotor_spin"),
  health: __t.i32(),
  weaponType: __t.u8().name("weapon_type"),
  weaponAmmoPrimary: __t.i32().name("weapon_ammo_primary"),
  weaponAmmoSecondary: __t.i32().name("weapon_ammo_secondary"),
  weaponAmmoTertiary: __t.i32().name("weapon_ammo_tertiary"),
  weaponLastFire: __t.timestamp().name("weapon_last_fire"),
  createdAt: __t.timestamp().name("created_at"),
  lastInputAt: __t.timestamp().name("last_input_at"),
});
