// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
  Rotation,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  entityId: __t.u64().name("entity_id"),
  vehicleType: __t.u8().name("vehicle_type"),
  get pos() {
    return Vec3;
  },
  get rot() {
    return Rotation;
  },
  createdAt: __t.timestamp().name("created_at"),
});
