// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  timeOfDay: __t.f32().name("time_of_day"),
  weather: __t.u8(),
  windSpeed: __t.f32().name("wind_speed"),
  cloudDensity: __t.f32().name("cloud_density"),
  fogDensity: __t.f32().name("fog_density"),
  lastWeatherChange: __t.timestamp().name("last_weather_change"),
});
